### ISSUE TITLE
Quaternion from non-uniform angular velcoity

### ISSUE THREAD

**Issue by hassity123** [sunsided/quaternion#1]
Hello, 
Would you please help me to convert the following  angular velocity data to quaternion ? I was trying to compute and got wrong result. The angular velocity data is attached
Thanks 
[angular velocity data.txt](https://github.com/sunsided/quaternion/files/4522311/angular.velocity.data.txt)

**Comment by sunsided** [comment]
I'm closing this one, since #2 captures the question a bit better.
