### ISSUE TITLE
Quaternion from Angular velocity

### ISSUE THREAD

**Issue by hassity123** [sunsided/quaternion#2]
delt=0.0164;                % Ts  
    ww(:,k)=[wwx(k),wwy(k),wwz(k)] ;     3 by 61      % angular velcity 
    qomega = quaternionFromAngularVelocity(ww(:,k), delt)' % quaternion from angular velocity 
    q(:,k) = quaternionMul(qomega, q)  % quaternion multiplication, q,   is initial 
    qq=q'                              % transpose  
    eulerA=quat2eul(qq);      % Euler angle from quat        
    rolld=eulerA(:,1);
    pitchd=eulerA(:,2);
    yawd=eulerA(:,3);
___
Fig.(1) is actual orientation angle computed from forward kinematics.  Fig(2). is desired rotation angle computed from angular velocity using your method.  Euler angles from actual rotation matrix are extracted using dcm2Angle from robotics  toolbox. Euler angle from quaternion is computed using quat2eul() from robotics toolbox. The result seems angle alpha and beta are switched. Also angle beta obtained by integration (your system) seems to have drift.  Can you please give me some feedback? 
Thanks  
![image](https://user-images.githubusercontent.com/34622175/80118066-e0ce7d80-85c2-11ea-85cc-b765e60d4da9.png)

**Comment by sunsided** [comment]
Haha, I totally forgot this repo even existed. :smile:

I'm assuming the data you're talking about is in #1?

I see the difference in the pictures, but I can't quite follow what you're doing - one reason being that I don't own MATLAB. Maybe we can work it out.

First of all, the data appears to be in degrees, but the `quaternionFromAngularVelocity` function requires input to be in radians - are you passing it in in a normalized way? The input is also expected to be in roll-pitch-yaw (XYZ) order - I can't tell from the data which order it is in. From what I can see in the [`quat2eul`](https://www.mathworks.com/help/robotics/ref/quat2eul.html) documentation, it seems to expect its input to be in ZYX order, that is yaw-pitch-roll. Does using `quat2eul(qq, "XYZ")` change anything?

**Comment by hassity123** [comment]
I solved the problem. It was the quat2eul and DCM2eul packages difference.   
Thank you so much.
